### ISSUE TITLE
Installation instructions unclear?

### ISSUE THREAD

**Issue by Slamy** [frafl/klangtrabant#1]
Hello frafl,

I'm currently trying your tool but I've some problems to get the example running.
`(/usr/share/texlive/texmf-dist/tex/generic/pgf/libraries/pgflibrarypatterns.cod
e.tex))...f/tex/latex/local/klangtrabant/klangtrabant/ktCommon.lua:84: attempt 
to index a nil value (upvalue 're')
stack traceback:
        ...f/tex/latex/local/klangtrabant/klangtrabant/ktCommon.lua:84: in function 'k
langtrabant.ktCommon.compileTable'
        .../tex/latex/local/klangtrabant/klangtrabant/Assembler.lua:71: in main chunk
        [C]: in function 'require'
        ...exmf/tex/latex/local/klangtrabant/klangtrabant/Macro.lua:23: in main chunk
        [C]: in function 'require'
        ...texmf/tex/latex/local/klangtrabant/klangtrabant/Book.lua:23: in main chunk
        [C]: in function 'require'
        [\directlua]:1: in main chunk.
l.96 }`
I've cloned this repo to ~/texmf/tex/latex/local/klangtrabant/ so I guess the installation should be ok. I've installed lpeg and re and also tried to use the supplied link to re and placed it in the same folder.
I have to say that I'm not very experienced with lua. I only have some experience with latex. So I assume I'm doing something wrong.
It seems to be related to `return re.compile(grStr,defs)` but I don't know what the issue is.

**Comment by frafl** [comment]
Many thanks for reporting this nasty bug (and sorry for the long delay).
Fixed with https://github.com/frafl/klangtrabant/commit/5dd7600d778789059fac43f24b452c94bfb72dd3
The instructions where correct, the code was wrong ;)
It did not actually look for re.lua in the klangtrabant folder, but only in the current folder (among others). I added an alternative way of installing re.lua for texlua to the README, which is what I actually used myself. But the way you installed it should also work now.
